### ISSUE TITLE
Program not working

### ISSUE THREAD

**Issue by chickensite** [jtagt/fortnite-health-tracker#2]
Hey,

I want to use this project, can you maybe help me.
I get an error everytime ( I don't want to use a server, I have filled in: "" for the raspberry pie host, then it says that theres no scheme supplied).
So I tried removing the " so I had this: "raspberry_pi_host": ,. This gave me the error: "json.decoder.JSONDecodeError: Expecting value: line 2 column 25 (char 26)"
Can you maybe help me with it?
Thanks

**Comment by jtagt** [comment]
yeah, just remove lines 59 and 60 
`            if not config['raspberry_pi_host'] is None:
                requests.get(config['raspberry_pi_host'])`
